### ISSUE TITLE
Eezo Ingot Bug

### ISSUE THREAD

**Issue by Cheezy16** [TeamFRM/TAIGA#132] opened 2017-02-27 22:29 UTC
I was using Storage Drawers' compacting drawers and noticed that the crafting recipe for eezo nuggets actually created 9 eezo ingots, instead of the intended 9 nuggets.

**Comment by IdleGandalf** [comment] 2017-07-09 16:01
Duplicate of #147

**Closed by IdleGandalf** 2017-07-09 16:01 UTC
